apiVersion: v1
kind: Service
metadata:
  name: observai-api
spec:
  selector:
    app: observai-api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
